language: python

python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"

install:
 - pip install -q "Django$DJANGO_VERSION"
 - pip install codecov

script:
 - coverage run --omit="tests/*" setup.py test

env:
 global:
   - SELENIUM_BROWSER=PhantomJS
 matrix:
   - DJANGO_VERSION=">=1.11,<2"
   - DJANGO_VERSION=">=1.10,<1.11"
   - DJANGO_VERSION=">=1.8,<1.9"

after_success:
 - codecov

matrix:
 exclude:
 # Django 1.10 and 1.11 don't run on Python 3.3
 - python: "3.3"
   env: DJANGO_VERSION=">=1.11,<2"
 - python: "3.3"
   env: DJANGO_VERSION=">=1.10,<1.11"
