dist: xenial

language: python

python:
 - "2.7"
 - "3.5"
 - "3.6"

addons:
  chrome: stable

install:
 - pip install -q "Django$DJANGO_VERSION"
 - pip install codecov
 - wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE
 - wget https://chromedriver.storage.googleapis.com/`cat LATEST_RELEASE`/chromedriver_linux64.zip
 - sudo unzip chromedriver_linux64.zip -d /usr/local/bin

script:
 - coverage run --omit="tests/*" setup.py test

env:
 global:
   - SELENIUM_WEBDRIVER=headless
 matrix:
   - DJANGO_VERSION=">=1.11,<2"
   - DJANGO_VERSION=">=2.2,<3"

after_success:
 - codecov

matrix:
 exclude:
 # Django 2.2 doesn't run on Python 2.7
 - python: "2.7"
   env: DJANGO_VERSION=">=2.2,<3"
